"""delete uniqueness of email

Revision ID: 2000d7af0810
Revises: 2dcfdb41bb70
Create Date: 2019-04-26 14:43:34.109784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2000d7af0810'
down_revision = '2dcfdb41bb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
