"""add img column to books

Revision ID: 4776a3a8ab5a
Revises: b360363046ee
Create Date: 2019-04-27 21:32:24.849257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4776a3a8ab5a'
down_revision = 'b360363046ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('img', sa.Text(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'img')
    # ### end Alembic commands ###
